# -*- coding: utf-8 -*-
"""model_architectureipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VGdHNsyYI3hDLz20DCFoWuo6Pmzu-yAW
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math

# === Utility ===
def get_timestep_embedding(timesteps, embedding_dim):
    half_dim = embedding_dim // 2
    emb = math.log(10000) / (half_dim - 1)
    emb = torch.exp(torch.arange(half_dim, device=timesteps.device) * -emb)
    emb = timesteps[:, None] * emb[None, :]
    emb = torch.cat([torch.sin(emb), torch.cos(emb)], dim=1)
    if embedding_dim % 2 == 1:
        emb = F.pad(emb, (0, 1))
    return emb

class SinusoidalPositionEmbeddings(nn.Module):
    def __init__(self, embedding_dim):
        super().__init__()
        self.embedding_dim = embedding_dim

    def forward(self, timesteps):
        return get_timestep_embedding(timesteps, self.embedding_dim)

# === Residual Block ===
class ResidualBlock3D(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, padding=1):
        super().__init__()
        self.same_channels = in_channels == out_channels

        self.conv1 = nn.Conv3d(in_channels, out_channels, kernel_size, padding=padding)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv3d(out_channels, out_channels, kernel_size, padding=padding)

        self.residual = nn.Identity() if self.same_channels else nn.Conv3d(in_channels, out_channels, kernel_size=1)

    def forward(self, x):
        residual = self.residual(x)
        out = self.conv1(x)
        out = self.relu(out)
        out = self.conv2(out)
        return self.relu(out + residual)

# === Encoder ===
class Encoder3D(nn.Module):
    def __init__(self, in_channels, base_channels=64, time_embed_dim=128):
        super().__init__()
        self.enc1 = nn.Sequential(
            ResidualBlock3D(in_channels, base_channels),
            ResidualBlock3D(base_channels, base_channels)
        )
        self.down1 = nn.Conv3d(base_channels, base_channels * 2, kernel_size=4, stride=2, padding=1)
        self.enc2 = nn.Sequential(
            ResidualBlock3D(base_channels * 2, base_channels * 2),
            ResidualBlock3D(base_channels * 2, base_channels * 2)
        )
        self.down2 = nn.Conv3d(base_channels * 2, base_channels * 4, kernel_size=4, stride=2, padding=1)
        self.enc3 = nn.Sequential(
            ResidualBlock3D(base_channels * 4, base_channels * 4),
            ResidualBlock3D(base_channels * 4, base_channels * 4)
        )
        self.time_proj1 = nn.Linear(time_embed_dim, in_channels)
        self.time_proj2 = nn.Linear(time_embed_dim, base_channels * 2)
        self.time_proj3 = nn.Linear(time_embed_dim, base_channels * 4)

    def forward(self, x, time_emb):
        B, _, D, H, W = x.shape
        t1 = self.time_proj1(time_emb).view(B, -1, 1, 1, 1)
        t2 = self.time_proj2(time_emb).view(B, -1, 1, 1, 1)
        t3 = self.time_proj3(time_emb).view(B, -1, 1, 1, 1)
        x1 = self.enc1(x + t1)
        x2 = self.enc2(self.down1(x1) + t2)
        x3 = self.enc3(self.down2(x2) + t3)
        return x1, x2, x3

# === Bottleneck ===
class Bottleneck3D(nn.Module):
    def __init__(self, in_channels, time_embed_dim=128):
        super().__init__()
        self.time_proj = nn.Linear(time_embed_dim, in_channels)
        self.block = nn.Sequential(
            ResidualBlock3D(in_channels, in_channels),
            ResidualBlock3D(in_channels, in_channels)
        )

    def forward(self, x, time_emb):
        B = x.shape[0]
        t = self.time_proj(time_emb).view(B, -1, 1, 1, 1)
        return self.block(x + t)

# === Decoder ===
class Decoder3D(nn.Module):
    def __init__(self, base_channels=64, out_channels=6, time_embed_dim=128):
        super().__init__()
        self.up1 = nn.ConvTranspose3d(base_channels * 4, base_channels * 2, kernel_size=4, stride=2, padding=1)
        self.dec1 = nn.Sequential(
            ResidualBlock3D(base_channels * 4, base_channels * 2),
            ResidualBlock3D(base_channels * 2, base_channels * 2)
        )
        self.up2 = nn.ConvTranspose3d(base_channels * 2, base_channels, kernel_size=4, stride=2, padding=1)
        self.dec2 = nn.Sequential(
            ResidualBlock3D(base_channels * 2, base_channels),
            ResidualBlock3D(base_channels, base_channels)
        )
        self.out_conv = nn.Conv3d(base_channels, out_channels, kernel_size=1)
        self.time_proj1 = nn.Linear(time_embed_dim, base_channels * 4)
        self.time_proj2 = nn.Linear(time_embed_dim, base_channels * 2)

    def forward(self, x3, x2, x1, time_emb):
        B = x3.shape[0]
        t1 = self.time_proj1(time_emb).view(B, -1, 1, 1, 1)
        t2 = self.time_proj2(time_emb).view(B, -1, 1, 1, 1)
        x = self.up1(x3)
        x = torch.cat([x, x2], dim=1)
        x = self.dec1(x + t1)
        x = self.up2(x)
        x = torch.cat([x, x1], dim=1)
        x = self.dec2(x + t2)
        return self.out_conv(x)

# === Final U-Net ===
class UNet3D_Full(nn.Module):
    def __init__(self, time_steps=6, image_channels=6, base_channels=64, time_embed_dim=128):
        super().__init__()
        self.encoder = Encoder3D(image_channels, base_channels, time_embed_dim)
        self.bottleneck = Bottleneck3D(base_channels * 4, time_embed_dim)
        self.decoder = Decoder3D(base_channels, out_channels=image_channels, time_embed_dim=time_embed_dim)
        self.time_mlp = nn.Sequential(
            SinusoidalPositionEmbeddings(time_embed_dim),
            nn.Linear(time_embed_dim, time_embed_dim),
            nn.ReLU()
        )

    def forward(self, x, t):
        time_emb = self.time_mlp(t)
        x1, x2, x3 = self.encoder(x, time_emb)
        bottleneck = self.bottleneck(x3, time_emb)
        return self.decoder(bottleneck, x2, x1, time_emb)

